//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBPIMEntities : DbContext
    {
        public DBPIMEntities()
            : base("name=DBPIMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBCARGO> TBCARGO { get; set; }
        public virtual DbSet<TBCARRO> TBCARRO { get; set; }
        public virtual DbSet<TBCARTAODECREDITO> TBCARTAODECREDITO { get; set; }
        public virtual DbSet<TBCATEGORIACARRO> TBCATEGORIACARRO { get; set; }
        public virtual DbSet<TBCIDADE> TBCIDADE { get; set; }
        public virtual DbSet<TBCLIENTE> TBCLIENTE { get; set; }
        public virtual DbSet<TBCONTATO> TBCONTATO { get; set; }
        public virtual DbSet<TBCOR> TBCOR { get; set; }
        public virtual DbSet<TBENDERECO> TBENDERECO { get; set; }
        public virtual DbSet<TBESTADO> TBESTADO { get; set; }
        public virtual DbSet<TBFUNCIONARIO> TBFUNCIONARIO { get; set; }
        public virtual DbSet<TBLOCACAO> TBLOCACAO { get; set; }
        public virtual DbSet<TBMARCACARRO> TBMARCACARRO { get; set; }
        public virtual DbSet<TBMODELOCARRO> TBMODELOCARRO { get; set; }
        public virtual DbSet<TBOPERADORACARTAO> TBOPERADORACARTAO { get; set; }
        public virtual DbSet<TBPAIS> TBPAIS { get; set; }
        public virtual DbSet<TBSETOR> TBSETOR { get; set; }
        public virtual DbSet<TBTIPOCONTATO> TBTIPOCONTATO { get; set; }
        public virtual DbSet<TBUSUARIO> TBUSUARIO { get; set; }
    }
}
