//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBCARGO
    {
        public TBCARGO()
        {
            this.TBFUNCIONARIO = new HashSet<TBFUNCIONARIO>();
        }
    
        public int NCDIDCARGO { get; set; }
        public string CNMNOME { get; set; }
        public string CDSDESCRICAO { get; set; }
        public Nullable<int> NCDIDSETOR { get; set; }
        public Nullable<bool> BIDATIVO { get; set; }
    
        public virtual ICollection<TBFUNCIONARIO> TBFUNCIONARIO { get; set; }
        public virtual TBSETOR TBSETOR { get; set; }
    }
}
