//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBCARTAODECREDITO
    {
        public TBCARTAODECREDITO()
        {
            this.TBLOCACAO = new HashSet<TBLOCACAO>();
        }
    
        public int NCDIDCARTAO { get; set; }
        public Nullable<int> NCDIDOPERADORACARTAO { get; set; }
        public string CCDRCARTAO { get; set; }
        public string NNRCODIGO { get; set; }
        public Nullable<System.DateTime> DDTVALIDADE { get; set; }
        public string CNMNOMECARTAO { get; set; }
        public Nullable<bool> BIDATIVO { get; set; }
        public Nullable<int> NCDIDCLIENTE { get; set; }
    
        public virtual TBOPERADORACARTAO TBOPERADORACARTAO { get; set; }
        public virtual ICollection<TBLOCACAO> TBLOCACAO { get; set; }
        public virtual TBCLIENTE TBCLIENTE { get; set; }
    }
}
