//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBCARRO
    {
        public TBCARRO()
        {
            this.TBLOCACAO = new HashSet<TBLOCACAO>();
        }
    
        public int NCDIDCARRO { get; set; }
        public string CCDCHASSI { get; set; }
        public string CCDPLACA { get; set; }
        public Nullable<System.DateTime> DDTDATAFABRICACAO { get; set; }
        public Nullable<System.DateTime> DDTDATAAQUISICAO { get; set; }
        public Nullable<int> NNRQTDEDELOCACOES { get; set; }
        public Nullable<int> NCDIDCORCARRO { get; set; }
        public Nullable<int> NCDIDMODELOCARRO { get; set; }
        public Nullable<bool> BIDLOCADO { get; set; }
        public Nullable<decimal> NVLDIARIA { get; set; }
    
        public virtual ICollection<TBLOCACAO> TBLOCACAO { get; set; }
        public virtual TBCOR TBCOR { get; set; }
        public virtual TBMODELOCARRO TBMODELOCARRO { get; set; }
    }
}
