//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBCIDADE
    {
        public TBCIDADE()
        {
            this.TBENDERECO = new HashSet<TBENDERECO>();
        }
    
        public int NCDIDCIDADE { get; set; }
        public string CDSCIDADE { get; set; }
        public Nullable<int> NCDIDESTADO { get; set; }
        public Nullable<bool> BIDATIVO { get; set; }
    
        public virtual ICollection<TBENDERECO> TBENDERECO { get; set; }
        public virtual TBESTADO TBESTADO { get; set; }
    }
}
