//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBCONTATO
    {
        public int NCDIDCONTATO { get; set; }
        public Nullable<int> NCDIDTIPOCONTATO { get; set; }
        public string CDSTELEFONE { get; set; }
        public Nullable<bool> BIDATIVO { get; set; }
    
        public virtual TBTIPOCONTATO TBTIPOCONTATO { get; set; }
    }
}
