//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBENDERECO
    {
        public int NCDIDENDEDERECO { get; set; }
        public string CDSLOGRADOURO { get; set; }
        public string NNRNUMERO { get; set; }
        public string CDSCOMPLEMENTO { get; set; }
        public Nullable<int> NCDIDCIDADE { get; set; }
    
        public virtual TBCIDADE TBCIDADE { get; set; }
    }
}
