//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBESTADO
    {
        public TBESTADO()
        {
            this.TBCIDADE = new HashSet<TBCIDADE>();
        }
    
        public int NCDIDESTADO { get; set; }
        public string CDSUF { get; set; }
        public string CDSSIGLA { get; set; }
        public Nullable<int> NCDIDPAIS { get; set; }
    
        public virtual ICollection<TBCIDADE> TBCIDADE { get; set; }
        public virtual TBPAIS TBPAIS { get; set; }
    }
}
