//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBFUNCIONARIO
    {
        public TBFUNCIONARIO()
        {
            this.TBUSUARIO = new HashSet<TBUSUARIO>();
        }
    
        public int NCDIDFUNCIONARIO { get; set; }
        public string CNMNOME { get; set; }
        public string CNMSOBRENOME { get; set; }
        public string CDSRG { get; set; }
        public string CDSCPF { get; set; }
        public Nullable<System.DateTime> DDTNASCIMENTO { get; set; }
        public Nullable<bool> BIDATIVO { get; set; }
        public Nullable<int> NCDIDCARGO { get; set; }
    
        public virtual TBCARGO TBCARGO { get; set; }
        public virtual ICollection<TBUSUARIO> TBUSUARIO { get; set; }
    }
}
