//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBMARCACARRO
    {
        public TBMARCACARRO()
        {
            this.TBMODELOCARRO = new HashSet<TBMODELOCARRO>();
        }
    
        public int NCDIDMARCACARRO { get; set; }
        public string CNMMARCACARRO { get; set; }
        public string CDSDESCRICAO { get; set; }
    
        public virtual ICollection<TBMODELOCARRO> TBMODELOCARRO { get; set; }
    }
}
