//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBMODELOCARRO
    {
        public TBMODELOCARRO()
        {
            this.TBCARRO = new HashSet<TBCARRO>();
        }
    
        public int NCDIDMODELOCARRO { get; set; }
        public string CDSMODELOCARRO { get; set; }
        public Nullable<int> NCDIDMARCACARRO { get; set; }
        public Nullable<int> NCDIDCATEGORIACARRO { get; set; }
    
        public virtual ICollection<TBCARRO> TBCARRO { get; set; }
        public virtual TBCATEGORIACARRO TBCATEGORIACARRO { get; set; }
        public virtual TBMARCACARRO TBMARCACARRO { get; set; }
    }
}
