//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBOPERADORACARTAO
    {
        public TBOPERADORACARTAO()
        {
            this.TBCARTAODECREDITO = new HashSet<TBCARTAODECREDITO>();
        }
    
        public int NCDIDOPERADORACARTAO { get; set; }
        public string CDSBANDEIRA { get; set; }
        public Nullable<bool> BIDATIVO { get; set; }
    
        public virtual ICollection<TBCARTAODECREDITO> TBCARTAODECREDITO { get; set; }
    }
}
