//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBPAIS
    {
        public TBPAIS()
        {
            this.TBESTADO = new HashSet<TBESTADO>();
        }
    
        public int NCDIDPAIS { get; set; }
        public string CDSPAIS { get; set; }
    
        public virtual ICollection<TBESTADO> TBESTADO { get; set; }
    }
}
