//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBSETOR
    {
        public TBSETOR()
        {
            this.TBCARGO = new HashSet<TBCARGO>();
        }
    
        public int NCDIDSETOR { get; set; }
        public string CNMNOME { get; set; }
        public string CDSDESCRICAO { get; set; }
        public Nullable<bool> BIDATIVO { get; set; }
    
        public virtual ICollection<TBCARGO> TBCARGO { get; set; }
    }
}
